  ----------------------------------------------------------------------------------------

/*
                                  EVENT REQUEST TYPE TABLE
*/

  ----------------------------------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS public.event_request_type_request_type_id_seq;
CREATE TABLE IF NOT EXISTS public.event_request_type
(
    request_type_id integer NOT NULL,
    request_description character varying(255) NOT NULL,
    request_life_cycle integer NOT NULL,
    CONSTRAINT request_type_request_type_id_pkey PRIMARY KEY (request_type_id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER SEQUENCE event_request_type_request_type_id_seq
    OWNED BY event_request_type.request_type_id;

INSERT INTO public.event_request_type (request_type_id, request_description, request_life_cycle)
VALUES (1, 'Client PTO Request', 48),
       (2, 'Team Lead PTO Request', -1),
       (3, 'HR PTO Request', 48),
       (4, 'CSE PTO Request', -1)

ON CONFLICT (request_type_id)
  DO NOTHING;


  ----------------------------------------------------------------------------------------

/*
                                   EVENT REQUEST TABLE
*/

  ----------------------------------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS public.event_request_event_request_id_seq;
CREATE TABLE IF NOT EXISTS public.event_request
(
    event_request_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_type_id integer NOT NULL,
    event_date_id integer NOT NULL,
    salt character varying(255) NOT NULL,
    hash character varying(255) NOT NULL,
    time_created timestamp NOT NULL,
    time_expires timestamp NOT NULL,
    approved boolean NOT NULL,
    auto_approved boolean NOT NULL,
    CONSTRAINT event_request_type_request_type_id_fkey FOREIGN KEY (request_type_id)
        REFERENCES public.event_request_type (request_type_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT event_date_event_date_id_fkey FOREIGN KEY (event_date_id)
        REFERENCES public.event_date (event_date_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER SEQUENCE event_request_event_request_id_seq
    OWNED BY event_request.event_request_id;
